// <auto-generated />
using System;
using GTEK.FSM.Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GTEK.FSM.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GtekFsmDbContext))]
    partial class GtekFsmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedWorkerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AssignmentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id")
                        .HasName("PK_Jobs");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Jobs_TenantId_Id");

                    b.HasIndex("TenantId", "AssignmentStatus")
                        .HasDatabaseName("IX_Jobs_TenantId_AssignmentStatus");

                    b.HasIndex("TenantId", "ServiceRequestId")
                        .HasDatabaseName("IX_Jobs_TenantId_ServiceRequestId");

                    b.HasIndex("TenantId", "AssignedWorkerUserId", "AssignmentStatus")
                        .HasDatabaseName("IX_Jobs_TenantId_AssignedWorkerUserId_AssignmentStatus");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id")
                        .HasName("PK_ServiceRequests");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_ServiceRequests_TenantId_Id");

                    b.HasIndex("TenantId", "ActiveJobId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ServiceRequests_TenantId_ActiveJobId")
                        .HasFilter("[ActiveJobId] IS NOT NULL");

                    b.HasIndex("TenantId", "CustomerUserId")
                        .HasDatabaseName("IX_ServiceRequests_TenantId_CustomerUserId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_ServiceRequests_TenantId_Status");

                    b.ToTable("ServiceRequests", (string)null);
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("EndsOnUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("StartsOnUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(25);

                    b.HasKey("Id")
                        .HasName("PK_Subscriptions");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Subscriptions_TenantId_Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Subscriptions_TenantId");

                    b.HasIndex("TenantId", "EndsOnUtc")
                        .HasDatabaseName("IX_Subscriptions_TenantId_EndsOnUtc");

                    b.HasIndex("TenantId", "PlanCode")
                        .HasDatabaseName("IX_Subscriptions_TenantId_PlanCode");

                    b.HasIndex("TenantId", "StartsOnUtc")
                        .HasDatabaseName("IX_Subscriptions_TenantId_StartsOnUtc");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id")
                        .HasName("PK_Tenants");

                    b.HasIndex("ActiveSubscriptionId")
                        .HasDatabaseName("IX_Tenants_ActiveSubscriptionId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tenants_Code");

                    b.HasIndex("Id", "ActiveSubscriptionId");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ExternalIdentity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Users_TenantId_Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Users_TenantId");

                    b.HasIndex("TenantId", "DisplayName")
                        .HasDatabaseName("IX_Users_TenantId_DisplayName");

                    b.HasIndex("TenantId", "ExternalIdentity")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_TenantId_ExternalIdentity");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.Job", b =>
                {
                    b.HasOne("GTEK.FSM.Backend.Domain.Aggregates.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Tenants_TenantId");

                    b.HasOne("GTEK.FSM.Backend.Domain.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssignedWorkerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Jobs_Users_TenantId_AssignedWorkerUserId");

                    b.HasOne("GTEK.FSM.Backend.Domain.Aggregates.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceRequestId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_ServiceRequests_TenantId_ServiceRequestId");
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.ServiceRequest", b =>
                {
                    b.HasOne("GTEK.FSM.Backend.Domain.Aggregates.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceRequests_Tenants_TenantId");

                    b.HasOne("GTEK.FSM.Backend.Domain.Aggregates.Job", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActiveJobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ServiceRequests_Jobs_TenantId_ActiveJobId");

                    b.HasOne("GTEK.FSM.Backend.Domain.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceRequests_Users_TenantId_CustomerUserId");
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.Subscription", b =>
                {
                    b.HasOne("GTEK.FSM.Backend.Domain.Aggregates.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Subscriptions_Tenants_TenantId");
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.Tenant", b =>
                {
                    b.HasOne("GTEK.FSM.Backend.Domain.Aggregates.Subscription", null)
                        .WithMany()
                        .HasForeignKey("Id", "ActiveSubscriptionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Tenants_Subscriptions_Id_ActiveSubscriptionId");
                });

            modelBuilder.Entity("GTEK.FSM.Backend.Domain.Aggregates.User", b =>
                {
                    b.HasOne("GTEK.FSM.Backend.Domain.Aggregates.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Tenants_TenantId");
                });
#pragma warning restore 612, 618
        }
    }
}
